apiVersion: v1
kind: Pod
metadata:
  name: nodeapp
  labels:
    app: nodeapp
spec:
  containers:
    - name: nodeapp
      image: dammy092002/nodeapp:latest
      ports:
        - containerPort: 8080
